image: golang:1.8.1-stretch

pipelines:
  default:
    - step:
        script:
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - OUT_FILE="${PACKAGE_PATH}/${BITBUCKET_REPO_SLUG}"
          # Copy repo to gopath
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          # Build it
          - GOOS=darwin GOARCH=amd64 go get -v
          - GOOS=darwin GOARCH=amd64 go build -v # Only build for osx for now
          - GOOS=darwin GOARCH=amd64 go test -v
          # Upload it
          - '[ "${BITBUCKET_BRANCH}" = "master" ] && curl -v -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${OUT_FILE}" || echo "Only uploading from master builds"'
