name: Tichu build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Enable manual triggers:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
#        with:
#          go-version: 1.23.5 -- see if it respects .tool-versions even though undocumented
      - run: go version
      - run: go build
      - run: echo ${{ github.event }}
      - run: echo ${{ github.ref }}
