name: Tichu build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Enable manual triggers:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.5
      - run: go version
      - run: go build
      - run: echo ${{ github.event }}
      - run: echo ${{ github.ref }}
      - uses: actions/upload-artifact@v4
        with:
          path: term-color

