name: Tichu build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Enable manual triggers:
  workflow_dispatch:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [
              macos-13, # for intel support
              macos-14,
              macos-15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.5
      - run: go version
      - run: go build
      - run: GOARCH='amd64' go build -o term-color-amd64
      - run: echo ${{ github.event.tag }}
      - run: echo ${{ github.ref }}
      - uses: actions/upload-artifact@v4
        with:
          name: term-color-${{ matrix.os }}
          path: term-color*

